### PR TITLE
Status initial commit

### LINKED ISSUE #1536: `git lfs status` crashes on new repos
### Steps to reproduce

```bash
$ git init .
$ git lfs status
Could not get the current ref

Errors logged to /path/to/repo/.git/lfs/objects/logs/20160926T120454.38945701.log
Use `git lfs logs last` to view the log.
```

### Error log
```
git-lfs/1.4.1 (GitHub; darwin amd64; go 1.7)
git version 2.10.0

$ git-lfs status
Could not get the current ref

Git can't resolve ref: "HEAD"
```

### PR DESCRIPTION
**Pull request by sinbad**
Fixes #1536 

Also makes added files appear in the staged area before the first commit.

### CODE REVIEW

File: lfs/scanner.go [hunk 1]
```diff
@@ -192,7 +195,8 @@ func (m *indexFileMap) Set(sha string, index *indexFile) {
 // ScanIndex returns a slice of WrappedPointer objects for all
 // Git LFS pointers it finds in the index.
 // Reports unique oids once only, not multiple times if >1 file uses the same content
-func ScanIndex() ([]*WrappedPointer, error) {
+// isFirstCommit must be true if this repo doesn't have any commits yet
+func ScanIndex(isFirstCommit bool) ([]*WrappedPointer, error) {
```
Comment (ttaylorr) [inline lfs/scanner.go]: Nice. What do you think about changing this to parameter to instead be the first ref to begin with? I think that might make the behavior of the function more obvious to the caller (instead of having to look and see what `true`/`false` means).

The `nullTreeish` constant makes this a little tricky to deal with, so maybe it could be called `InitialCommit` or something similar?

`ScanIndex("HEAD")`, `ScanIndex(InitialCommit)`.

Comment (technoweenie) [inline lfs/scanner.go]: I like this idea. Could even add a global like `HeadRef` or something too.

Comment (sinbad) [inline lfs/scanner.go]: I wanted callers to ScanIndex not to have to know exactly what they needed to do to support pre-initial commit but you're right that when reading the code afterwards just seeing `false` is less useful than seeing `InitialCommit` so I'll do that. 

`HeadRef` would be good in theory but because that would introduce an extra `git` call just to derive `HEAD` in 99% of cases, and when most of the time it actually makes sense to abort before the first commit - `status` is one of the few where it makes sense to do something useful - I won't do this for now. If you can think of some other cases where it's useful to get the null tree automatically we can add it?
